{{$namespaces := 5}}
{{$deploymentsPerNamespace := 1}}
{{$concurrentWorkers := 1}}

name: Simple Test
automanagedNamespaces: {{$namespaces}}
deleteStaleNamespaces: true
deleteAutomanagedNamespaces: false
tuningSets:
  - name: Sequence
    parallelismLimitedLoad:
      parallelismLimit: 1
  - name: Concurrently
    parallelismLimitedLoad:
      parallelismLimit: {{$concurrentWorkers}}
steps:
- name: Starting measurement for waiting for pods
  measurements:
  - Identifier: WaitForRunningDeployments
    Method: WaitForControlledPodsRunning
    Params:
      action: start
      apiVersion: apps/v1
      kind: Deployment
      labelSelector: group = load
      operationTimeout: 15m
- name: Creating Pods
  phases:
    - namespaceRange:
        min: 1
        max: {{$namespaces}}
      replicasPerNamespace: {{$deploymentsPerNamespace}}
      tuningSet: Concurrently
      objectBundle:
      - basename: small-service
        objectTemplatePath: deployment/service.yaml
      - basename: small-deployment
        objectTemplatePath: deployment/configmap.yaml
      - basename: small-deployment
        objectTemplatePath: deployment/secret.yaml
      - basename: small-deployment
        objectTemplatePath: deployment/deployment.yaml
        templateFillMap:
          ReplicasMin: 1
          ReplicasMax: 1
          SvcName: small-service
- name: Waiting for pods to be running
  measurements:
  - Identifier: WaitForRunningDeployments
    Method: WaitForControlledPodsRunning
    Params:
      action: gather
- name: Deleting Deployments
  phases:
  - namespaceRange:
      min: 1
      max: {{$namespaces}}
    replicasPerNamespace: 0
    tuningSet: Concurrently
    objectBundle:
      - basename: small-deployment
        objectTemplatePath: deployment/configmap.yaml
      - basename: small-deployment
        objectTemplatePath: deployment/secret.yaml
      - basename: small-deployment
        objectTemplatePath: deployment/deployment.yaml
      - basename: small-service
        objectTemplatePath: deployment/service.yaml
- name: Waiting for pods to be deleted
  measurements:
  - Identifier: WaitForRunningDeployments
    Method: WaitForControlledPodsRunning
    Params:
      action: gather
